### PR TITLE
Update documentation links in Settings UI

### PR DESCRIPTION
**Pull request by boaz0**
Replace link prefix from https://access.redhat.com/documentation/en-us/openshift_container_platform to https://access.redhat.com/documentation/en-us/cost_management_service/2021

closes COST-977

//cc @dlabrecq @nlcwong @spank50

### CODE REVIEW

**Review by ddonahue007 — DISMISSED** [review]
LGTM

**Review by dlabrecq — APPROVED** [review]

**Comment by boaz0** [comment]
Sorry @ddonahue007 and @dlabrecq I had to update the PR with changes from the main branch. Can you review this again?
Thanks.

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Review by dccurtis — APPROVED** [review]

**Pull request merged**
