### PR TITLE
Fixing oci import bloat!

### PR DESCRIPTION
**Pull request by lcouzens**
Fixes [COST-####](https://issues.redhat.com/browse/COST-####)

Changes proposed in this PR:
*
*

Testing Instructions:
1. Run `this command` ...
2. Ingest this data `with this other command` ...
3. Expect to see this result:
   ```
   GET http://localhost:8000/api/endpoint

   {json: response}
   ```
4.
5.

---
Additional Context:

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
8475e733-a44d-4aed-9761-a0e2e97d70a8
9124c7ef-98eb-4135-9642-3f4395492081

**Review by myersCody — APPROVED** [review]
LGTM!

**Review by maskarb — APPROVED** [review]
lgtm!

**Pull request merged**
