### PR TITLE
Cost 2034 deadlock info

### PR DESCRIPTION
**Pull request by Red-HAP**
## Jira Ticket

[COST-2034](https://issues.redhat.com/browse/COST-2034)

## Description

This adds new Exception classes that will ingest `psycopg2` driver exceptions and gather extended information that will make it easier to log. 

The intent here is to gather as much information as we can regarding the dreaded `deadlock detected` exception in order to get more data so that we can figure out a fix for the issue.

## Smoke Tests

```
=========================== short test summary info ============================
FAILED lib64/python3.6/site-packages/iqe_cost_management/tests/rest_api/v1/test_source.py::test_api_gcp_source_raw_calc
= 1 failed, 607 passed, 1 skipped, 6171 deselected, 2 warnings in 613.86s (0:10:13) =
```

[Full Log](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/2992/console)

## Testing

There's not an easy way to test this... 

Most of the functionality test is in the unit test file.

### CODE REVIEW

**Comment by lcouzens** [comment]
Last smoke run failures
test_source.test_api_aws_source_crud (Failed to create cost model :confused: )
test_source.test_api_aws_source_raw_calc (AWS account error unrelated to these changes)

**Review by maskarb — DISMISSED** [review]
Looks good to me. Just one question.

**Review by maskarb — APPROVED** [review]
Sweet, thanks for making that change! Looks quite a bit cleaner.

**Review by maskarb — APPROVED** [review]

**Comment by Red-HAP** [comment]
## Lil' Smokies

```
 =========================== short test summary info ============================
 FAILED lib64/python3.6/site-packages/iqe_cost_management/tests/rest_api/v1/test_source.py::test_api_gcp_source_raw_calc
 ERROR lib64/python3.6/site-packages/iqe_cost_management/tests/rest_api/v1/test_source.py::test_api_aws_source_raw_calc
 = 1 failed, 27 passed, 6751 deselected, 2 warnings, 1 error in 444.04s (0:07:24) =
```

### Failure

```
test_api_gcp_source_raw_calc:

 supplied = 1204.0, expected = 1193.241223063, tolerance = 10 assert_message = 'Raw calculated value does not match report value'
```

### Error

```
test_api_aws_source_raw_calc

 E           botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
```

[Full Log](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/3012/console)

**Pull request merged**
