### PR TITLE
[COST-3649] Populate AWS cost category summary table for type ahead

### PR DESCRIPTION
**Pull request by myersCody**
## Jira Ticket

[COST-3649](https://issues.redhat.com/browse/COST-3649)

## Description

This change will populate the aws cost category summary table for type ahead functionality & potentially the RBAC functionality later on. 

## Testing

1. Checkout Branch
2. make load-test-customer-data data_source=AWS
3. 
```
postgres=# select key, values, usage_account_id, account_alias_id, cost_entry_bill_id from reporting_awscategory_summary;
     key      |         values         | usage_account_id | account_alias_id | cost_entry_bill_id
--------------+------------------------+------------------+------------------+--------------------
 env          | {ephemeral,prod}       | 9999999999990    |                3 |                  7
 env          | {ephemeral,prod}       | 9999999999991    |                4 |                  7
 env          | {ephemeral,prod}       | 9999999999992    |                5 |                  7
 env          | {ephemeral,prod}       | 9999999999993    |                6 |                  7
 env          | {ephemeral,prod}       | 9999999999994    |                7 |                  7
 env          | {ephemeral,prod}       | 9999999999995    |                8 |                  7
 env          | {ephemeral,prod}       | 9999999999999    |                  |                  7
 env          | {ephemeral,prod}       | 9999999999990    |                3 |                  8
 env          | {ephemeral,prod}       | 9999999999991    |                4 |                  8
 env          | {ephemeral,prod}       | 9999999999992    |                5 |                  8
 env          | {ephemeral,prod}       | 9999999999993    |                6 |                  8
 env          | {ephemeral,prod}       | 9999999999994    |                7 |                  8
 env          | {ephemeral,prod}       | 9999999999995    |                8 |                  8
 env          | {ephemeral,prod}       | 9999999999999    |                  |                  8
 env          | {ephemeral,prod,stage} | 9999999999999    |                  |                 10
 Organization | {Ninja}                | 9999999999999    |                  |                 10
 env          | {ephemeral,prod,stage} | 9999999999999    |                  |                  9
 Organization | {Ninja}                | 9999999999999    |                  |                  9
 ```

### CODE REVIEW

**Comment by myersCody** [comment]
Blocked by: https://github.com/project-koku/koku/pull/4267

**Review by samdoran — DISMISSED** [review]
The SQL could probably use more scrutiny than I'm able to provide. The rest looks good.

**Review by maskarb — DISMISSED** [review]

**Review by maskarb — APPROVED** [review]
lgtm!

**Review by samdoran — APPROVED** [review]

**Pull request merged**
