### PR TITLE
[COST-2635] remove refresh views task

### PR DESCRIPTION
**Pull request by adberglund**
Fixes [COST-2635](https://issues.redhat.com/browse/COST-2635)

Changes proposed in this PR:
* This reworks the mat view refresh task to just mark a manifest as done
* We need cost model cost calculations to complete before marking everything as done, and we optionally launch that task. So for now this keeps marking the manifest complete in a separate task that can be called after all other tasks finish
* Chain calls with the mat view task are replaced with just the cost model task

Testing Instructions:
1. Run `this command` ...
2. Ingest this data `with this other command` ...
3. Expect to see this result:
   ```
   GET http://localhost:8000/api/endpoint

   {json: response}
   ```
4.
5.

---
Additional Context:

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
18389e1d-fb55-4c20-bd14-05a857ee722f
db691db4-2636-4cbb-a140-bc0da4508848

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
5e180d5d-7ed5-40f2-a0c6-750ae06425d1
b01fb321-de5d-442f-9d4f-967febac414a

**Review by lcouzens — APPROVED** [review]
lgtm

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3e13f3dc-9544-4be5-a5a2-24f7f71738fc
953777c3-aa32-42d6-a591-df5584f08a16

**Pull request merged**
