### PR TITLE
COST-2569: cluster grouping for OCP on ALL missing GCP.

### PR DESCRIPTION
**Pull request by myersCody**
## Jira Ticket

[COST-2569](https://issues.redhat.com/browse/COST-2569)

## Description

This change will have ocp on gcp data returned when going to the following endpoint: 
- http://localhost:8000/api/cost-management/v1/reports/openshift/infrastructures/all/storage/?group_by[cluster]=*&filter[cluster]=test_cost_ocp

## Testing

There was a smoke test disabled because of this smoke. I reenabled it and ran it to confirm my fix:
```
    ENV_FOR_DYNACONF=local iqe tests plugin cost_management -k 'test_api_ocp_on_cloud_storage_validate_data_integrity' --pdb
```
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================ 4 passed, 10298 deselected, 618 warnings in 1325.08s (0:22:05) ============================================
```

####  The issues with OCP on GCP cost not showing up correctly with OCP on ALL.
- The ocp on gcp storage endpoint, creates the storage table based off of the [following service_aliases](https://github.com/project-koku/koku/blob/31e95bc60a69760c73255bae4d135ba850f499d3/koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_storage_summary_p.sql#L49):
```
AND service_alias IN ('Filestore', 'Storage', 'Cloud Storage', 'Data Transfer')
```

I also needed to remove the strict unit filter of `GB-Mo`, because for GCP the units come in as `gibibyte month`. So, that filter was moved to the `or_filter`.

## Notes

```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================ 4 passed, 10298 deselected, 618 warnings in 1325.08s (0:22:05) ============================================
(.iqe_venv) cmyers@cmyers1-mac iqe-cost-management-plugin % ENV_FOR_DYNACONF=local iqe tests plugin cost_management -k 'test_api_ocp_on_cloud_storage_validate_data_integrity' --pdb
```

### CODE REVIEW

**Comment by myersCody** [comment]
Failed Smoke Tests 😢 

[tests.rest_api.v1.test_hcs.test_api_gcp_hcs_report_finalization](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/7747/testReport/junit/tests.rest_api.v1/test_hcs/test_api_gcp_hcs_report_finalization/)
[tests.rest_api.v1.test_source.test_api_ocp_on_azure_source_raw_calc](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/7747/testReport/junit/tests.rest_api.v1/test_source/test_api_ocp_on_azure_source_raw_calc/)
[tests.rest_api.v1.test_source.test_api_ocp_on_gcp_source_raw_calc](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/7747/testReport/junit/tests.rest_api.v1/test_source/test_api_ocp_on_gcp_source_raw_calc/)

I will need to look into these more tomorrow.

**Comment by myersCody** [comment]
Successful Smoke Results: https://ibutsu.apps.ocp4.prod.psi.redhat.com/runs/d2ce2dca-ecf3-4318-aa57-e32eaa8b8875#results-list

**Comment by myersCody** [comment]
One test failure with a timeout: 
- https://ci.ext.devshift.net/job/project-koku-koku-pr-check/8093/testReport/junit/tests.rest_api.v1/test__all_data_ingest/test_api_gcp_ingest_multi_sources/

**Comment by myersCody** [comment]
100% passing smoke tests: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/8198/

**Review by samdoran — APPROVED** [review]

**Pull request merged**
