### PR TITLE
Log a warning instead of an error when deleting manifest that does no…

### PR DESCRIPTION
**Pull request by nbon12**
Addresses #1513 
Log a -warning- INFO when deleting a manifest file that does not exist.

### CODE REVIEW

**Comment by adberglund** [comment]
@blentz This is part of a series of issues raised by Sentry that went through backlog refinement. There's several places that we were abusing log.error and it was causing static in our sentry alerts. Here, we're just trying to clean up a temporary file, so it it doesn't exists it's not really an error in our program, just a case we're already catching. I don't think the log message here hurts anything, although it could be updated to say that the file doesn't exist. 

I agree with your assessment, but I think the problem is actually in the report downloader's `get_report_context_for_date` methods where `_get_manifest` is called and effectively returns garbage. We then continue to try to process that garbage instead of stopping. We can open a separate issue to deal with that, but this one was just a quick "fix the logging" issue.

**Comment by blentz** [comment]
@adberglund - Understood, but that doesn't really change my objection. I don't see how changing the logging priority is fixing anything. It may be silencing the noise generated by a new tool, but as you said - that's not the part that needs fixing. That's basically the same thing as just adding `pylint: disable` and ignoring the underlying issue.

I'd prefer to see us fix the root cause. There's no need to change this code at all if the problem is elsewhere.

**Comment by adberglund** [comment]
@blentz This issue went through backlog refinement as-is, and as a team we decided we wanted to start by "fixing" the logging level. This accomplishes that. We can certainly also open a new issue to address the underlying issue. I believe it really only happens with QA runs tests, so I'd call it low priority, but we can have it in the backlog.

**Comment by blentz** [comment]
I'm not asking to re-scope the issue or change what was decided during grooming. Apologies if that's how my comment sounded.

I'm asking to set the log level to a more appropriate level. Everything else I mentioned is broader context and doesn't need to affect this PR. Again, apologies if it sounded like I was asking for something bigger than that.

The issue opened by Sentry suggests `INFO`. I'm suggesting `DEBUG` or `pass`. `WARNING` is too high of a logging level. So, please pick between `INFO`, `DEBUG`, or `pass`, or help me understand what raises this to the level of `WARNING`.

Secondly, yes, please open a new issue to address the root cause in the `_get_manifest` method. I agree that is a low priority bugfix.

Once the log level is at the appropriate level, I think this PR is fine.

**Pull request merged**
