### PR TITLE
[COST-3016] Cover CTES that use volume tables

### PR DESCRIPTION
**Pull request by adberglund**
## Jira Ticket

[COST-3016](https://issues.redhat.com/browse/COST-3016)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

### CODE REVIEW

**Review by chambridge — DISMISSED** [review]
lgtm

**Comment by kholdaway** [comment]
🎈

**Comment by adberglund** [comment]
[🚬 ](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/6835/)

**Review by lcouzens — APPROVED** [review]

**Pull request merged**
