### PR TITLE
[COST-2578] change report_periods to report_period_ids

### PR DESCRIPTION
**Pull request by cgoodfred**
Fixes [COST-2578](https://issues.redhat.com/browse/COST-2578)

Changes proposed in this PR:
*
*

Testing Instructions:
1. Run `this command` ...
2. Ingest this data `with this other command` ...
3. Expect to see this result:
   ```
   GET http://localhost:8000/api/endpoint

   {json: response}
   ```
4.
5.

---
Additional Context:
Talked with Eva about the 2 smoke failures here, she said its a known thing and unrelated: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/4886/

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
d0000e6f-b827-4c1b-9e0a-b89ed1d03538
f6962ec6-2117-4897-89fd-9f88534ca899

**Review by adberglund — APPROVED** [review]

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
6818da13-4e44-4967-9d15-9cbadbd3c861
be263181-6ac0-4f82-bfb6-1e40959c42df

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
61e42e70-bdde-4d80-84c6-e14d227a7658
d1141a86-1633-47bf-be26-0d7455ac4e4d

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
a54bedf9-743c-4e43-a43b-832f2ee08ad1
f8be2da9-e8f7-4ac7-b240-03e8f777671a

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
62047594-e2ed-4be4-b070-922f410c9a92
9102df33-e39b-4eea-b5cf-1a08d6528e86

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
15140ed5-5c24-45c1-a267-0127e30d8798
57e5f2bd-1b34-495d-821a-c4225f7d753e

**Pull request merged**
