### PR TITLE
Updated the issue template to reflect current issue style.

### PR DESCRIPTION
**Pull request by adberglund**
I _think_ this provides a slightly more accurate template for how our issues look right now.

### CODE REVIEW

**Comment by chambridge** [comment]
I'm fine with these updates, problem is how to find a balance with user story templating and bugs. I sometimes think the template should be geared more towards bugs as I can keep a gist of the story template but I rather that a bug gets opened with the appropriate info. We used the following format on quipucords to attempt both.
___



## Specify type:
- Bug
- Enhancement

### Priority:
- Blocker
- High
- Medium
- Low
___

## Description:
Provide a description of the issue being raised.

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

## Bug Report

### Version Information:
Commit information.

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.

**Comment by chambridge** [comment]
Looks like Github may have added a feature here:
image


https://help.github.com/articles/creating-issue-templates-for-your-repository/

**Comment by adberglund** [comment]
Awesome! Let's use github's feature, yeah?

**Comment by chambridge** [comment]
Created a new PR: https://github.com/project-koku/koku/pull/117

**Pull request closed without merging**
