### PR TITLE
[COST-3878] distributed cost is high for ranked list logic

### PR DESCRIPTION
**Pull request by myersCody**
## Jira Ticket

[COST-3878](https://issues.redhat.com/browse/COST-3878)

---

### Problem one: High Distributed Cost

On main:
- http://localhost:8000/api/cost-management/v1/reports/openshift/costs/?end_date=2023-05-31&filter[limit]=11&filter[offset]=0&group_by[project]=*&order_by[distributed_cost]=desc&start_date=2023-05-01

Has a higher distributed_cost than expected. [This change](https://github.com/project-koku/koku/pull/4404/files#diff-7856c4ba653f802f9901aa185f9dfcd3754d01fe20a6fa824b6443d31b88d48aR1155) Fixed that issue. We needed to tell the order by logic to not overwrite the value. 

---

### Problem Two: PVC cost not being credited for the platform projects.

@pedrolp85  created a smoke test to test this (`plopezpe/update_cost_distribution_clusters_with_storage_resources`)

Locally run:
```
ENV_FOR_DYNACONF=local iqe tests plugin cost_management --trace -k test_api_cost_model_ocp_cost_distribution_user_projects_cpu_all --pdb
```

Results:
```
=========================================================================================== 1 passed, 10575 deselected, 111 warnings in 112.48s (0:01:52) ===========================================================================================
```
^ Run on main and this branch to see the difference. The sql changes to `koku/masu/database/sql/openshift/cost_model/distribute_platform_cost.sql` fixed this problem.

---
### Problem Three: Default ordering overwrites distributed ordering for ranked list logic.
1. [COST-3881](https://issues.redhat.com/browse/COST-3881)
@esebesto wrote a smoke test to help replicate this problem: `test_api_ocp_cost_filtered_top_projects`

I pushed up one minor fix to these tests here: 
- https://gitlab.cee.redhat.com/insights-qe/iqe-cost-management-plugin/-/merge_requests/1633

After running these tests locally:

```
========================================================================================== 168 passed, 10577 deselected, 748 warnings in 169.98s (0:02:49) ==========================================================================================
```

### CODE REVIEW

**Comment by myersCody** [comment]
Smoke Tests: 
- https://ci.ext.devshift.net/job/project-koku-koku-pr-check/9765/

**Comment by pedrolp85** [comment]
tested overhead cost into user project  according to cpu usage  with all cost models (distribute all, worker, platform and None) with storage resources added into the ymal.
I will modify this tests into our main Asap to include this in out pipelines

**Comment by myersCody** [comment]
This [commit](https://github.com/project-koku/koku/pull/4404/commits/435a19a15c385affe896a58737080a4bf7d1122c) is really to fix [COST-3881](https://issues.redhat.com/browse/COST-3881) However, that was blocked by the changes in this PR. 

I also needed to make updates to the test in the issue, here: https://gitlab.cee.redhat.com/insights-qe/iqe-cost-management-plugin/-/merge_requests/1633

**Comment by myersCody** [comment]
No failed Smoke tests: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/9799/

**Comment by pedrolp85** [comment]
Added storage resources to other 2 yaml and run all cost distribution tests, included top items with cody's fix and all looks good

**Review by lcouzens — APPROVED** [review]

**Pull request merged**
