### PR TITLE
COST-1293 changed description filter method to allow more than one filter

### PR DESCRIPTION
**Pull request by Dostonbek1**
Fixes [COST-1293](https://issues.redhat.com/browse/COST-1293)

Changes proposed in this PR:
* Changed cost-model 'description' filter method to the same as 'name' field to allow more than one filter 

Testing Instructions:
1. Send a request to the following endpoint with 2 or more filters for 'description' field:
   - http://127.0.0.1:8000/api/cost-management/v1/cost-models/?limit=10&offset=0&description=model,aws
2. Verify this request returns data

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4a2762c5-13b3-4df6-9aa6-0fa6c4ff7cc5
93318709-6f15-4dc1-9ca0-8ad5a968a923

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
2589cb8f-a555-4ef9-a87b-1438b594ff15
53cccd89-b203-4df8-a9e5-4b4014b98986

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
32f41506-45ce-41d5-84ff-f0e40b6f8114
882b3fc5-3453-4a15-b972-b1d541427637

**Review by shannon-donahue — APPROVED** [review]
lgtm

**Pull request merged**
