### PR TITLE
Remove codecov and update README

### PR DESCRIPTION
**Pull request by djnakabaale**
## Description

- remove codecov from dev dependencies as its [not installable via pip](https://pypi.org/project/codecov/) and causes package installation failure
- update README file since the `--sequential` flag was [removed from pipenv](https://github.com/pypa/pipenv/pull/5348)

### CODE REVIEW

**Review by adberglund — APPROVED** [review]

**Comment by maskarb** [comment]
Does `tox` run ok locally with these changes?

**Comment by djnakabaale** [comment]
> Does `tox` run ok locally with these changes?

Yes

```
  py39: commands succeeded
  congratulations :)
```

**Comment by maskarb** [comment]
> > Does `tox` run ok locally with these changes?
> 
> Yes
> 
> ```
>   py39: commands succeeded
>   congratulations :)
> ```

What happens when you recreate the tox env:
```
tox -r
```

**Comment by djnakabaale** [comment]
> > > Does `tox` run ok locally with these changes?
> > 
> > 
> > Yes
> > ```
> >   py39: commands succeeded
> >   congratulations :)
> > ```
> 
> What happens when you recreate the tox env:
> 
> ```
> tox -r
> ```

Yeah, that's blowing up

```
Collecting pipenv
  Using cached pipenv-2023.3.20-py3-none-any.whl (2.9 MB)
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov

================================================================================================================================================================================= log end ==================================================================================================================================================================================
ERROR: could not install deps [pipenv, codecov]; v = InvocationError('/path/to/koku/.tox/py39/bin/python -m pip install pipenv codecov', 1)
```

**Review by maskarb — APPROVED** [review]
lgtm!

**Pull request merged**
