### PR TITLE
forecast `_key_results_by_date` fix

### PR DESCRIPTION
**Pull request by maskarb**
Changes proposed in this PR:
* Update `_key_results_by_date` so that it does not result in a IndexError when a cost_term is an empty list.
* the cost_term can be an empty list when `_predict` is not able to calculate a prediction due to too few data points.

### CODE REVIEW

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
89f987c3-e14c-498b-9716-1c8924b10cc2
f6e15086-3c73-49a7-812f-6ff036c9843e

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
267ea644-7bb9-4eb8-bdb1-4138a828aaf2
8be9a2e0-bffe-4c2f-9608-3b0ebd60c344

**Review by ddonahue007 — DISMISSED** [review]
LGTM

**Comment by ddonahue007** [comment]
LGTM

**Review by ddonahue007 — APPROVED** [review]

**Pull request merged**
