### PR TITLE
Update settings page so Cost Savings is visible in non dev mode

### PR DESCRIPTION
**Pull request by ddonahue007**
Closes: https://issues.redhat.com/browse/COST-2092

Update settings page to expose AWS Cost Savings settings

Screen Shot 2021-11-19 at 10 08 45 AM

Database table before and after a changes are made via the settings page
Screen Shot 2021-11-19 at 10 19 39 AM

### CODE REVIEW

**Review by abaiken — APPROVED** [review]
LGTM!

**Review by shannon-donahue — DISMISSED** [review]
LGTM

**Review by dlabrecq — DISMISSED** [review]
unit tests failed, but otherwise looks good

**Comment by abaiken** [comment]
I updated the unit tests from 3 to 6 because it looks like it returns 3 new components for cost type: 
```
[
{'component': 'plain-text', 'label': 'Enable tags and labels', 'name': 'api.settings.tag_management.form-text', 'variant': 'h2'}, 
{'component': 'plain-text-with-links', 'text': 'Enable your data source labels to be used as tag keys for report grouping and filtering. Changes will be reflected within 24 hours. <link>Learn more</link>', 'linkProps': [{'href': 'https://access.redhat.com/documentation/en-us/cost_management_service/2021/html-single/managing_cost_data_using_tagging/index#assembly-configuring-tags-and-labels-in-cost-management'}], 'name': 'api.settings.tag_management.form-text'}, 
{'component': 'dual-list-select', 'name': 'api.settings.tag-management.enabled', 'isTree': 'true', 'options': [{'label': 'OpenShift labels', 'hasBadge': 'true', 'children': [{'value': 'openshift-qa', 'label': 'qa'}, {'value': 'openshift-storageclass', 'label': 'storageclass'}, {'value': 'openshift-app', 'label': 'app'}, {'value': 'openshift-version', 'label': 'version'}, {'value': 'openshift-environment', 'label': 'environment'}]}, {'label': 'Amazon Web Services tags', 'hasBadge': 'true', 'children': [{'value': 'aws-app', 'label': 'app'}, {'value': 'aws-storageclass', 'label': 'storageclass'}, {'value': 'aws-version', 'label': 'version'}, {'value': 'aws-environment', 'label': 'environment'}]}, {'label': 'Azure tags', 'hasBadge': 'true', 'children': [{'value': 'azure-app', 'label': 'app'}, {'value': 'azure-storageclass', 'label': 'storageclass'}, {'value': 'azure-version', 'label': 'version'}, {'value': 'azure-environment', 'label': 'environment'}]}, {'label': 'Google Cloud Platform tags', 'hasBadge': 'true', 'children': [{'value': 'gcp-test_storage_key', 'label': 'test_storage_key'}, {'value': 'gcp-vm_key_proj2', 'label': 'vm_key_proj2'}]}], 'leftTitle': 'Disabled tags/labels', 'rightTitle': 'Enabled tags/labels', 'initialValue': ['openshift-storageclass', 'openshift-environment', 'openshift-version', 'aws-app', 'aws-environment'], 'clearedValue': []}, 
{'component': 'plain-text', 'label': 'Show cost as (Amazon Web Services Only)', 'name': 'api.settings.cost_type', 'variant': 'h2'}, 
{'component': 'plain-text', 'label': 'Select the preferred way of calculating upfront costs, either through savings plans or subscription fees. This feature is available for Amazon Web Services cost only.', 'name': 'api.settings.cost_type', 'variant': 'p'}, 
{'component': 'select', 'name': 'api.settings.cost_type', 'options': [{'value': 'unblended_cost', 'label': 'Unblended', 'description': 'Usage cost on the day you are charged'}, {'value': 'savingsplan_effective_cost', 'label': 'Amortized', 'description': 'recurring and/or upfront costs are distributed evenly across the month'}, {'value': 'blended_cost', 'label': 'Blended', 'description': 'Using a blended rate to calculate cost usage'}], 'initialValue': 'unblended_cost', 'FormGroupProps': {'style': {'width': '400px'}}}
]
```

**Review by abaiken — APPROVED** [review]

**Pull request merged**
