### PR TITLE
[COST-2012] azure partable sql/processing

### PR DESCRIPTION
**Pull request by cgoodfred**
This PR is to change the processing for azure away from materialized views and to partitioned tables. In order to test, just run `make create-test-customer` and `make load-test-customer-data` and then verify that you see azure related costs on the endpoints and that the azure partitioned tables are filled in the DB. 

SMOKES:
The PR check had a failing smoke: `test_api_cost_model_ocp_on_azure_markup_calculation` However, I think that is the ephemeral job acting up and not a real failure.

```
=========================== short test summary info ============================
ERROR lib64/python3.6/site-packages/iqe_cost_management/tests/rest_api/v1/test__cost_model.py::test_api_cost_model_ocp_on_azure_markup_calculation
= 1407 passed, 14 skipped, 4709 deselected, 10 warnings, 1 error in 1295.22s (0:21:35) =
```

But I ran the same test suite locally: 
```
========================= 1408 passed, 14 skipped, 4709 deselected, 9 warnings in 716.05s (0:11:56) ==========================
```

### CODE REVIEW

**Review by maskarb — APPROVED** [review]
LGTM! Just one suggestion:

**Comment by lcouzens** [comment]
So the 1 failing test here is actually failing on main too.

**Review by maskarb — APPROVED** [review]
Nicely done!

**Pull request merged**
