### PR TITLE
COST-2013: Convert gcp mat views to parition tables.

### PR DESCRIPTION
**Pull request by myersCody**
smokees:
- https://ci.ext.devshift.net/job/project-koku-koku-pr-check/2519/

### CODE REVIEW

**Comment by myersCody** [comment]
ayyy no gcp smoke test failures: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/2717/
🎉

**Review by maskarb — APPROVED** [review]
lgtm!

**Comment by maskarb** [comment]
The `test_api_gcp_settings_tag_enablement` due to a timing issue. It passes on its own.

**Pull request merged**
