### PR TITLE
[COST-4210] - remove ProviderDBAccessor for notifications and utils

### PR DESCRIPTION
**Pull request by maskarb**
## Jira Ticket

[COST-4210](https://issues.redhat.com/browse/COST-4210)

## Description

This is the first of several PRs to delete the ProviderDBAccessor.

This PR removes the ProviderDBAccessor from the notifications flow and all masu.utils. I also commented out unused notification functions. We can uncomment when we build the task to make use of those funcs.

### CODE REVIEW

**Review by cgoodfred — APPROVED** [review]
LGTM as long as smokes pass

**Review by cgoodfred — APPROVED** [review]

**Review by lcouzens — APPROVED** [review]

**Pull request merged**
