### PR TITLE
[COST-3558] Remove old processing tables

### PR DESCRIPTION
**Pull request by adberglund**
## Jira Ticket

[COST-3558](https://issues.redhat.com/browse/COST-3558)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

### CODE REVIEW

**Review by maskarb — APPROVED** [review]
lgtm!

**Review by maskarb — APPROVED** [review]
lgtm!

**Review by maskarb — DISMISSED** [review]
lgtm!

**Comment by lcouzens** [comment]
Smoke test failures here are a little :suspect: test_api_aws_ingest_single_source, test_api_azure_ingest_single_source

**Review by maskarb — APPROVED** [review]
lgtm!

**Pull request merged**
