### PR TITLE
Test that partitiion manager trigger delete works from separate schema

### PR DESCRIPTION
**Pull request by Red-HAP**
Test that the partition manager truncate, drop works from a different schema.

See the testing code for a testing scenario. This is to help support scripting operations in prod, stage when necessary and fixes an original omission on my part during development.

## Smokes

```
=== 608 passed, 1 skipped, 6170 deselected, 2 warnings in 518.40s (0:08:38) ====
```

### CODE REVIEW

**Comment by lcouzens** [comment]
Last smoke results on this pr = 2 failed, 5105 passed, 688 skipped, 881 deselected, 4 warnings, 103 errors in 6041.21s (1:40:41) =

**Review by adberglund — APPROVED** [review]

**Pull request merged**
