### PR TITLE
RHINENG-9884 updated openapi.json - added description for ROS recomme…

### PR DESCRIPTION
**Pull request by PreetiW**
## Jira Ticket

[RHINENG-9884](https://issues.redhat.com/browse/RHINENG-9884)

## Description
updated openapi.json - added description for ROS recommendation API endpoint

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Release Notes
- [ ] proposed release note

### CODE REVIEW

**Comment by lcouzens** [comment]
@PreetiW whats the exact intention here? To render a link in the description for the refs? I could be wrong but I'm not entirely sure if this will work. 
image

**Comment by PreetiW** [comment]
> @PreetiW whats the exact intention here? To render a link in the description for the refs? I could be wrong but I'm not entirely sure if this will work. image

Hello @lcouzens, thank you for providing review on the PR. My aim here is to provide information about the `ROS OpenAPI Json` file for the developers outside our team. Hence I added a description mentioning where the OpenAPI Json file is for the `ref`. Do let me know if you have any better suggestion to achieve the same so that anyone looking at the OpenAPI Json file understands to look at https://github.com/RedHatInsights/ros-ocp-backend/blob/main/openapi.json for ROS APIs. Let me know if you have any question around the same 🙌🏻

**Comment by lcouzens** [comment]
@PreetiW did you manage to find an alternative solution for this, or should we close this for now?

**Comment by lcouzens** [comment]
I'm going to close this for now. Feel free to reopen or create a new PR when you have something. :bow:

**Pull request closed without merging**
