### PR TITLE
[COST-3313] - distribute by resource usage (GCP) 

### PR DESCRIPTION
**Pull request by maskarb**
## Jira Ticket

[COST-3313](https://issues.redhat.com/browse/COST-3313)
## Description

* Move away from reporting_ocpgcpcostlineitem_daily_summary_p table in favor of reporting_ocpgcpcostlineitem_project_daily_summary_p everywhere.
* Distributes GCP costs based on usage instead of counts <<<< this is the fix for COST-3313
* Updates the OCP-on-GCP provider map to drop the _by_project report-types. All results now come from the reporting_ocpgcpcostlineitem_project_daily_summary_p.

### CODE REVIEW

**Review by myersCody — COMMENTED** [review]
Awesome work Michael!
I noticed while reviewing this PR, with these changes the following columns are calculated in the same way:
```
credit_amount == pod_credit
unblended_cost == pod_cost
markup_cost == project_markup_cost
```

Which kind of makes these `(pod_credit, pod_cost, project_markup_cost)` redundant now, which to me is a good sign.

Maybe we should just store zero for these project specific columns in this PR, and then open a tech debt issue later to remove them since they are now unneeded. However, I also understand this is a high priority issue for a customer, so we can just open a tech debt issue to remove them and ship it too. So, I wanted to get your thoughts. I also don't mind creating the tech debt issue if you want to get rolling onto the next one.

----

On the IQE side of things

1) The `test_api_ocp_on_gcp_cost_negative_filtering_tags` in your ibutsu results. I merged in main to kick if it off again to see if it is consistent. I am also running them locally now.

2) Also, I ran the smoke tests that were failing because of [COST-3314](https://issues.redhat.com/browse/COST-3314) on this PR and they passed :woohoo:
```-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================ 24 passed, 10241 deselected, 484 warnings in 510.70s (0:08:30) ============================================```

**Review by myersCody — APPROVED** [review]
Let me know if you against me opening up a tech debt issue to remove the now redundant project columns from the DB. However, that is totally a separate issue, awesome work on this @maskarb 🏆

**Comment by maskarb** [comment]
> Let me know if you against me opening up a tech debt issue to remove the now redundant project columns from the DB. However, that is totally a separate issue, awesome work on this @maskarb 🏆

Yea, you're welcome to open the issue. We do indeed have a lot of tech debt building up. I do want to remove the redundant stuff in a future PR tho.

**Comment by myersCody** [comment]
The technical debit issue mentioned in the discussion above: https://issues.redhat.com/browse/COST-3332

**Pull request merged**
