### PR TITLE
Added docker-compose file for M1 & created auto-reload workaround of …

### PR DESCRIPTION
**Pull request by Dostonbek1**
Fixes [COST-2608](https://issues.redhat.com/browse/COST-2608)

Changes proposed in this PR:
* Added a new separate docker-compose file for M1
* Created auto-reload workaround of watchdog
* Updated documentation

### CODE REVIEW

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Comment by ddonahue007** [comment]
I added the `hot-fix-smoke-tests` label and setup to retest. I believe we are requiring all PR's run the min smokes to make sure deployment happens.

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
42138606-89c6-4469-8b43-253f50774821
c81b7c80-7580-41c3-a6a9-a73f5870d848

**Pull request merged**
