### PR TITLE
Change measurement label to Cost for Node, Cluster & PVC metrics

### PR DESCRIPTION
**Pull request by boaz0**
closes COST 775

//cc @lcouzens

### CODE REVIEW

**Review by adberglund — COMMENTED** [review]
I think what we're actually measuring here is the `Count` of each resource. How do you feel about switching this to `Count`?

**Comment by boaz0** [comment]
@lcouzens what do you think? `Count` seems more accurate here than `Cost`.

**Comment by lcouzens** [comment]
Yeh I think Andrew is correct, count sounds good to me! :+1:

**Review by blentz — APPROVED** [review]

**Comment by boaz0** [comment]
Thank you @adberglund & @blentz !

**Pull request merged**
