### PR TITLE
Use pre-commit and black for formatting.

### PR DESCRIPTION
**Pull request by chambridge**
* Use [pre-commit](https://pre-commit.com) to run code corrections as part of commit hooks
* Use [black](https://black.readthedocs.io/en/stable/) for code formatting to try and eliminate time spent running lint

```
$ pre-commit run --all-files
Reorder python imports...................................................Passed
pyupgrade................................................................Passed
black....................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
Flake8...................................................................Passed
```

### CODE REVIEW

**Comment by maskarb** [comment]
Screen Shot 2020-02-06 at 5 43 49 PM

🥇

**Comment by adberglund** [comment]
💯 💯 💯

**Comment by abaiken** [comment]
🎉 👍

**Comment by chambridge** [comment]
@blentz absolutely. Just opened this for discussion. See comment in Slack: https://ansible.slack.com/archives/CAAN6CRB2/p1581026923448900

**Comment by myersCody** [comment]
This is pretty neat, I really like it 👍

**Pull request merged**
