### PR TITLE
[COST-3590] OCP on cloud precursor delete task

### PR DESCRIPTION
**Pull request by adberglund**
## Jira Ticket

[COST-3590](https://issues.redhat.com/browse/COST-3590)

## Description

* This change will move the `DELETE` operations for OCP on Cloud to their own tasks that must complete before we being the actually summary / `INSERT` operations. 
* This also introduces logic to conduct a `TRUNCATE` when we are summarizing a full month's data.

## Testing

1. Checkout Branch
2. `make create-test-customer` and `make load-test-customer-data`
3. Watch delete tasks happen before summary
4. Run http://127.0.0.1:5042/api/cost-management/v1/report_data/?provider_uuid=411b0741-f8ca-40f1-aacc-3e050487482f&schema=org1234567&start_date=2023-02-01&end_date=2023-02-28
 using the cloud infra provider that drives OCP on Cloud costs and run for a full month. Watch TRUNCATEs be performed. Adjust to not a full month and watch DELETEs occur.
 
## Notes

...

### CODE REVIEW

**Comment by adberglund** [comment]
Possible smoke test: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/8534/

**Comment by djnakabaale** [comment]
Logs are looking good to me

<details>
      <summary>
        for TRUNCATE on OCPGCP:
      </summary>

```
koku-koku-worker-1  | [2023-03-22 16:01:12,584] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 {'message': 'Getting OpenShift on Cloud infrastructure map for 5ea8d2be-fbce-4b69-8b1b-b2f9009c5350', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:01:12,585] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 {'message': 'Using start date: 2023-02-01', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:01:12,585] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 {'message': 'Using end date: 2023-02-28', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:01:12,627] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 {'message': 'update_cost_model_costs skipped. schema_name: org1234567, provider_uuid: 5ea8d2be-fbce-4b69-8b1b-b2f9009c5350', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:01:12,678] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 Set report_summary_updater = GCPReportParquetSummaryUpdater
koku-koku-worker-1  | [2023-03-22 16:01:12,679] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 {'message': 'Starting report data summarization for provider uuid: 5ea8d2be-fbce-4b69-8b1b-b2f9009c5350.', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:01:12,681] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 Triggering TRUNCATE reporting_ocpgcpcostlineitem_project_daily_summary_p_2023_02
koku-koku-worker-1  | [2023-03-22 16:01:12,966] INFO 7645b789-fae0-4814-ba32-a6e0678c5046 Finished TRUNCATE on reporting_ocpgcpcostlineitem_project_daily_summary_p_2023_02 in 0.284261 seconds.
```
</details>
  
<details>
      <summary>
        for DELETE on OCPGCP:
      </summary>

```
koku-koku-worker-1  | [2023-03-22 16:04:13,855] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b {'message': 'Getting OpenShift on Cloud infrastructure map for 5ea8d2be-fbce-4b69-8b1b-b2f9009c5350', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:04:13,855] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b {'message': 'Using start date: 2023-03-01', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:04:13,855] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b {'message': 'Using end date: 2023-03-22', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:04:13,888] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b {'message': 'update_cost_model_costs skipped. schema_name: org1234567, provider_uuid: 5ea8d2be-fbce-4b69-8b1b-b2f9009c5350', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:04:13,939] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b Set report_summary_updater = GCPReportParquetSummaryUpdater
koku-koku-worker-1  | [2023-03-22 16:04:13,939] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b {'message': 'Starting report data summarization for provider uuid: 5ea8d2be-fbce-4b69-8b1b-b2f9009c5350.', 'tracing_id': None}
koku-koku-worker-1  | [2023-03-22 16:04:13,940] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b Deleting records from reporting_ocpgcpcostlineitem_project_daily_summary_p for source 5ea8d2be-fbce-4b69-8b1b-b2f9009c5350 from 2023-03-01T00:00:00 to 2023-03-22T00:00:00
koku-koku-worker-1  | [2023-03-22 16:04:13,940] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b Triggering DELETE on reporting_ocpgcpcostlineitem_project_daily_summary_p from 2023-03-01T00:00:00 to 2023-03-22T00:00:00.
koku-koku-worker-1  | [2023-03-22 16:04:13,966] INFO b4affbd4-9473-4677-ba39-d14fbbb18a7b Finished DELETE on reporting_ocpgcpcostlineitem_project_daily_summary_p in 0.025795 seconds.
```

</details>

**Review by djnakabaale — APPROVED** [review]

**Pull request merged**
