### PR TITLE
[COST-2602] Update unit handling in Azure SQL

### PR DESCRIPTION
**Pull request by adberglund**
Fixes [COST-2602](https://issues.redhat.com/browse/COST-2602)

Changes proposed in this PR:
* This updates some SQL to use a regex to see if a field is numeric so we don't fail on non-numeric units

Testing Instructions:
1. Run `this command` ...
2. Ingest this data `with this other command` ...
3. Expect to see this result:
   ```
   GET http://localhost:8000/api/endpoint

   {json: response}
   ```
4.
5.

---
Additional Context:

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4d43e569-db08-429d-8e42-144cad9ee1af
c0f07cc4-18c6-4b7f-aec9-0729dd7ed7d7

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
459bbc73-ddda-46f7-86a0-70f1a9fbcedc
527dd955-290d-44f5-b67b-de027fe78444

**Review by djnakabaale — APPROVED** [review]
lgtm

**Pull request merged**
