### PR TITLE
[COST-3631] Try change to OCP on GCP SQL

### PR DESCRIPTION
**Pull request by adberglund**
## Jira Ticket

[COST-3631](https://issues.redhat.com/browse/COST-3631)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

### CODE REVIEW

**Comment by adberglund** [comment]
Smoke https://ci.ext.devshift.net/job/project-koku-koku-pr-check/8668/

**Review by lcouzens — APPROVED** [review]

**Pull request merged**
