### PR TITLE
RHIROS-1292 Make ROS OCP API spec available under Cost-Mgmt API doc

### PR DESCRIPTION
**Pull request by srdeotarse**
## Jira Ticket

[RHIROS-1292](https://issues.redhat.com/browse/RHIROS-1292) [ROS-OCP] Make API specifications available under Insights API documentation

## Description

This PR consists **Cost-Mgmt** side of ``openapi.json`` file changes to include **ROS-OCP Backend API** endpoints under ``Optimizations`` tag using ``$ref``

https://github.com/RedHatInsights/ros-ocp-backend/pull/133 - Along with **ROS-OCP Backend** side of ``openapi.json`` file changes, whenever the API spec file is updated, the changes will automatically reflect for all **ROS OCP Backend API** endpoints.

## Screenshots
Screenshot from 2023-10-12 13-11-49

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes
Need to wait for https://github.com/RedHatInsights/ros-ocp-backend/pull/133 to get merged, then change ``$ref`` to link to https://raw.githubusercontent.com/RedHatInsights/ros-ocp-backend/main/openapi.json
...

### CODE REVIEW

**Comment by srdeotarse** [comment]
@chambridge could you please assign someone to review this PR, Thanks!

**Review by lcouzens — APPROVED** [review]

**Comment by srdeotarse** [comment]
@chambridge When referenced URLs become invalid, this type of error is shown on Swagger UI - 

image

**Pull request merged**
