### PR TITLE
implement unleash-client for currency and settings endpoints

### PR DESCRIPTION
**Pull request by maskarb**
This PR adds the necessary library and clowdapp changes so that we can use Unleash for feature flags. The implementation in this PR toggles the `/currency` endpoint and the currency settings in the `/settings` endpoint.

Testing:
Start all the service, including unleash:
```
in koku repo:
make docker-up-min
```

With Unleash running, go to [`http://localhost:4242/`](http://localhost:4242/)
You should see:

image

Enter any email address (this does not matter). You should see a page like this:

feature-toggles

Click on [`cost-currency-api-view`](http://localhost:4242/#/features/strategies/cost-currency-api-view) and you will see:

cost-currency-api-view

Go to [`/currency` endpoint](http://localhost:8000/api/cost-management/v1/currency/) and see data:

image

Delete the `10001` schema from the [`schema-strategy`](http://localhost:4242/#/features/strategies/cost-currency-api-view) in unleash:

image

Wait 15 seconds, refresh the [`/currency` endpoint](http://localhost:8000/api/cost-management/v1/currency/). You should see a 404 returned:

image

### CODE REVIEW

**Review by adberglund — DISMISSED** [review]

**Comment by maskarb** [comment]
There doesn't seem to be any kind of interest in using unleash for these endpoints, so closing this PR.

**Pull request closed without merging**
