### PR TITLE
COST-325: Fix multiple group_by org_unit_id for cost report.

### PR DESCRIPTION
**Pull request by myersCody**
#### Problem breakdown 

Jira Issue: https://issues.redhat.com/browse/COST-325

Currently there isn't a good way to do multiple group_by for both `group_by[or:org_unit_id]` & `group_by[org_unit_id]`. There wasn't really a solution for `group_by[or:org_unit_id]` because the key comes in as `or:org_unit_id` which means this check was never being hit: https://github.com/project-koku/koku/blob/master/koku/api/report/aws/query_handler.py#L186
```
if "org_unit_id" in self.parameters.parameters.get("group_by"):
            org_unit_applied = True
            # remove the org unit and add in group by account
            org_unit_group_by_data = self.parameters.parameters.get("group_by").pop("org_unit_id")
```

As for multiple group_bys for `group_by[org_unit_id]`, even though it would hit the condition we would only truly look at the first element in the list here: https://github.com/project-koku/koku/blob/master/koku/api/report/aws/query_handler.py#L197
```
org_unit_object = (
   AWSOrganizationalUnit.objects.filter(org_unit_id=org_unit_group_by_data[0])
   .filter(account_alias__isnull=True)
   .first()
)
```

The overall struggle for this issue was ultimately deciding what each multiple group by should look like in the return. After a lengthy discussion with Ash, we decided that the `group_by[or:org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002` would return the sub orgs 1 level deep for both OU_001 & OU_002. 

#### How to test
Here is a little diagram of the current tree structure:  https://docs.google.com/presentation/d/1Oa2njqavJVm7PJc_h8wqFx9uBrO2mER7WFzbPBG_-OQ/edit?usp=sharing

Run `make load-aws-org-unit-tree` to populate the tree in the database.

Hit the multiple `group_by[or:org_unit_id]` endpoint: 
- http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[or:org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002&order_by[cost]=desc
- We need to make sure that the sub ous for `OU_001` and `OU_002` are shown in the results. Per the diagram above that would be `OU_003` & `OU_005`.

We also need to check that the single group by still works:
- http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=R_001, You should still see `OU_001` & `OU_002` in the returns.
- http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[oorg_unit_id]=OU_001&group_by[or:region]=*
- http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_001&group_by[or:account]=*

The bad combinations caught in the serializer:
-  http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002
- http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_001&group_by[org_unit_id]=OU_002
- http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[or:org_unit_id]=*

### CODE REVIEW

**Comment by myersCody** [comment]
After a discussion with @cgoodfred this morning, we are thinking that the filtering issue Corey has been working on may also fix the multiple group by issue we are seeing here. It makes a lot of sense when you think about it because when you do a `group_by[org_unit_id]` you are actually doing a group by account and a filter on the org unit id. Therefore fixing the filter to  calculate cost all the way down will likely fix some of the group by issues that we are seeing as well. We are going to sync up later today to confirm.

**Comment by myersCody** [comment]
After another chat with Corey we decided to go with my implementation cause it covered more fringe cases

**Comment by cgoodfred** [comment]
I was trying out a few different queries and when I look at an endpoint with multiple group_by's where one has an or and the other doesn't, for example: http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_002&group_by[or:org_unit_id]=OU_001 

I get the following TypeError:

```[2020-07-24 17:31:31,174] ERROR None Internal Server Error: /api/cost-management/v1/reports/aws/costs/
Traceback (most recent call last):
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/Users/cgoodfred/CostDevelopment/koku/koku/api/report/view.py", line 159, in get
    output = handler.execute_query()
  File "/Users/cgoodfred/CostDevelopment/koku/koku/api/report/aws/query_handler.py", line 270, in execute_query
    query_data = self.format_sub_org_results(query_data_results, query_data, sub_orgs_dict)
  File "/Users/cgoodfred/CostDevelopment/koku/koku/api/report/aws/query_handler.py", line 147, in format_sub_org_results
    for value in account.get("values"):
TypeError: 'NoneType' object is not iterable
[2020-07-24 17:31:31,178] INFO None {'method': 'GET', 'path': '/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002', 'status': 500, 'request_id': None, 'account': '10001', 'username': 'user_dev', 'is_admin': 'True'}
[2020-07-24 17:31:31,178] ERROR None "GET /api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002 HTTP/1.1" 500 177805```

**Comment by myersCody** [comment]
> I was trying out a few different queries and when I look at an endpoint with multiple group_by's where one has an or and the other doesn't, for example: [http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_002&group_by[or:org_unit_id]=OU_001](http://127.0.0.1:8000/api/cost-management/v1/reports/aws/costs/?group_by%5Borg_unit_id%5D=OU_002&group_by%5Bor:org_unit_id%5D=OU_001)
> 
> I get the following TypeError:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
>     response = self.handle_exception(exc)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
>     raise exc
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/Users/cgoodfred/.local/share/virtualenvs/koku-YSwwm01t/lib/python3.6/site-packages/django/views/decorators/vary.py", line 20, in inner_func
>     response = func(*args, **kwargs)
>   File "/Users/cgoodfred/CostDevelopment/koku/koku/api/report/view.py", line 159, in get
>     output = handler.execute_query()
>   File "/Users/cgoodfred/CostDevelopment/koku/koku/api/report/aws/query_handler.py", line 270, in execute_query
>     query_data = self.format_sub_org_results(query_data_results, query_data, sub_orgs_dict)
>   File "/Users/cgoodfred/CostDevelopment/koku/koku/api/report/aws/query_handler.py", line 147, in format_sub_org_results
>     for value in account.get("values"):
> TypeError: 'NoneType' object is not iterable
> [2020-07-24 17:31:31,178] INFO None {'method': 'GET', 'path': '/api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002', 'status': 500, 'request_id': None, 'account': '10001', 'username': 'user_dev', 'is_admin': 'True'}
> [2020-07-24 17:31:31,178] ERROR None "GET /api/cost-management/v1/reports/aws/costs/?group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002 HTTP/1.1" 500 177805```
> ```

@cgoodfred Whoops, sorry I missed this review on Friday. Too focused on pagination work 😂  I will take a look now and see if I can get a fix up for this.

**Comment by myersCody** [comment]
@cgoodfred First off, really good catch on this! It was definitely a scenario I missed while working my way through this issue. So, after looking into the `group_by[org_unit_id]=OU_002&group_by[or:org_unit_id]=OU_001` use case I definitely agree that it needs fixed, I am just struggling to figure out what would be the right fix here.

As of right now,  I can think of three possible solutions to the problem. 

**Solution One:**
`group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002` is not a valid option and should be kicked back in the serializer

**Solution Two:** 
`group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002` is a valid option, but is treated the same as two `or:org_unit_id` group_bys

**Solution Three:**
`group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002` is a valid option, but my initial design of the multiple org unit id group by should be revisited to rethink what we actually want to be returned for the following scenarios:

- two `org_unit_id` group_by, (Just to recap my current design treats this as the intersection of sub orgs for the org unit ids passed into the group_bys)
- two `or:org_unit_id` group by, (Just to recap my current design treats this as the union of the sub orgs for the org_unit_ids passed into the group_by)
- one `org_unit_id` group_by and one `or:org_unit_id` group by (Needs further design and implementation)

------

Just as a little side note, @cgoodfred I don't expect you to know the answer here cause I don't either 😂.  I just wanted to get the possible solutions out in the open for everyone to start thinking about. I am also totally open to other solutions here too. 

**Next Step:**

We need to loop in other members of the team to get their thoughts regarding what is the best solution to this problem. Unfortunately, with all the M8 planning meetings this week, it may be hard to squeeze this design discussion into the loop.

**Comment by myersCody** [comment]
Quick Update: After talking with @dccurtis he suggested that we may be trying to cover scenarios that the UI will not actually use. So I have set up a meeting with @dlabrecq tomorrow to talk through his use cases for multiple org unit group by scenario. After that discussion we should have a clear picture of what kind of group by scenarios we should run across and the expected result. If a scenario is unlikely to be used, I am going to invalidate it in the serializer.

**Comment by myersCody** [comment]
Quick Update:
----
@cgoodfred @dccurtis 

After a discussion with @dlabrecq , we agreed that the following multiple group by combinations didn't really make sense from the UI perspective:
- `group_by[org_unit_id]=OU_001&group_by[org_unit_id]=OU_002`
- `group_by[org_unit_id]=OU_001&group_by[or:org_unit_id]=OU_002` 

Therefore for now, we are going to disable these combinations in the serializer. We can always revisit them if the design for the UI changes. Therefore, multiple org_unit_id group_by s will always be a `group_by[or:org_unit_id]=OU_001`. I will get these changes up in the branch hopefully by the end of the day.

**Pull request merged**
