### PR TITLE
[COST-4423] update missed sql file for cluster info

### PR DESCRIPTION
**Pull request by lcouzens**
## Jira Ticket

[COST-4423](https://issues.redhat.com/browse/COST-4423)

## Description

This change will update the OCP sql file for infra maps (missed first time around)

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

### CODE REVIEW

**Comment by lcouzens** [comment]
gcp-smoke-tests 100% passed

**Review by djnakabaale — APPROVED** [review]
Besides codecov coverage complaining, looks good to me 👍🏾

**Comment by pedrolp85** [comment]
Given the smoke results of the PR:
```
https://ci.ext.devshift.net/job/koku-pipeline-pr-check-main/1125/
https://ci.ext.devshift.net/job/koku-pipeline-pr-check-main/1126/
```

locally:
```
PASSED tests/rest_api/v1/test__cost_model.py::test_api_cost_model_ocp_on_gcp_markup_calculation
PASSED tests/rest_api/v1/test__cost_model.py::test_api_cost_model_gcp_markup_calculation 
PASSED tests/data_setup/test_all_data_ingest.py::test_api_ocp_on_gcp_ingest_multi_sources
PASSED tests/data_setup/test_all_data_ingest.py::test_api_gcp_ingest_multi_sources
PASSED tests/data_setup/test_all_data_ingest_check.py::test_api_ocp_on_gcp_ingest_multi_sources_check[cost]
PASSED tests/data_setup/test_all_data_ingest_check.py::test_api_ocp_on_gcp_ingest_multi_sources_check[memory]
PASSED tests/data_setup/test_all_data_ingest_check.py::test_api_ocp_on_gcp_ingest_multi_sources_check[compute]
PASSED tests/data_setup/test_all_data_ingest_check.py::test_api_ocp_on_gcp_ingest_multi_sources_check[volume]
PASSED tests/data_setup/test_all_data_ingest_check.py::test_api_gcp_ingest_multi_sources_check[cost]
PASSED tests/data_setup/test_all_data_ingest_check.py::test_api_gcp_ingest_multi_sources_check[instance]
PASSED tests/data_setup/test_all_data_ingest_check.py::test_api_gcp_ingest_multi_sources_check[storage]
```


I would say this solves the regression introduced by
 [COST-4423] - Initial work for cluster/source info page (#4924)

**Review by pedrolp85 — APPROVED** [review]
LGTM

**Review by djnakabaale — APPROVED** [review]

**Pull request merged**
