### PR TITLE
[COST-4313] - subscription_name migrations

### PR DESCRIPTION
**Pull request by lcouzens**
## Jira Ticket

[COST-4313](https://issues.redhat.com/browse/COST-4313)

## Description

This change will add subscription_name for azure to all the relevant OCP on azure tables.

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

### CODE REVIEW

**Review by bacciotti — APPROVED** [review]

**Review by djnakabaale — APPROVED** [review]
lgtm 👍🏾

**Pull request merged**
