### PR TITLE
[COST-3828] Add tag mapping model.

### PR DESCRIPTION
**Pull request by myersCody**
## Jira Ticket

[COST-3828](https://issues.redhat.com/browse/COST-3828)

## Description

This change will add the tag mapping models.

## Notes

...

### CODE REVIEW

**Review by bacciotti — DISMISSED** [review]

**Comment by myersCody** [comment]
Original Smoke Test: https://ci.ext.devshift.net/job/koku-pipeline-pr-check-main/750/

**Review by cgoodfred — APPROVED** [review]

**Pull request merged**
