### PR TITLE
[COST-2534] ocp on cloud cluster association

### PR DESCRIPTION
**Pull request by adberglund**
Fixes [COST-2534](https://issues.redhat.com/browse/COST-2534)

Changes proposed in this PR:
* When we run OCP summary, we should check to see if the cluser is associated with a cloud provider

Testing Instructions:
1. Run `this command` ...
2. Ingest this data `with this other command` ...
3. Expect to see this result:
   ```
   GET http://localhost:8000/api/endpoint

   {json: response}
   ```
4.
5.

---
Additional Context:

### CODE REVIEW

**Review by djnakabaale — APPROVED** [review]
lgtm

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3f4f0387-2fd1-40dd-9712-4c7f3c3e5765
b45f617b-a4fa-4cdc-aaa1-4f6564d761dc

**Comment by adberglund** [comment]
[🚬 ](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/4847/)

**Comment by adberglund** [comment]
[🚬 ](https://ci.ext.devshift.net/job/project-koku-koku-pr-check/4852/) GCP

**Review by djnakabaale — APPROVED** [review]
lgtm

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
2dc90979-0a0f-4cec-b060-f890b1972e6a
71d6dadf-9fb7-47ef-8f81-8d2c4552b970

**Pull request merged**
