### PR TITLE
GCP: Add migration changes for partition_time & credits.

### PR DESCRIPTION
**Pull request by myersCody**

### CODE REVIEW

**Comment by myersCody** [comment]
Two test failures: 
```
Test Result (2 failures / +1)
lib64.python3.6.site-packages.iqe_cost_management.tests.rest_api.v1.test_source.test_api_multi_ingest_ocp_source
lib64.python3.6.site-packages.iqe_cost_management.tests.rest_api.v1.test_user.test_api_settings_azure_tag_enablement
```

**Review by maskarb — APPROVED** [review]
LGTM! Since there was a run with only 2 failures which were unrelated to this PR, let's go ahead and merge.

**Pull request merged**
