### PR TITLE
Adding local OCI downloader flow

### PR DESCRIPTION
**Pull request by lcouzens**
Fixes [COST-2384](https://issues.redhat.com/browse/COST-2384)

Changes proposed in this PR:
* Adding local OCI downloader flow
* Adding models for OCI processing
* Adding processing files
* Adding SQL for processing

Testing Instructions:
1. Add some local csv's to local download dir
2. Add oci-local provider
3. See oci_cost_line_items(_daily) and oci_usage_line_items(_daily) created and populated
4. See summary tables populated in postgres

---
Additional Context:

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4bec41d4-af68-4089-a727-a24496d5f181
d4dc323a-9349-4934-b7df-c2547dc1723c

**Comment by myersCody** [comment]
*Trino Tables*
```
trino:acct10001> select count(*) from oci_cost_line_items;
 _col0
-------
  2220
trino:acct10001> select count(*) from oci_cost_line_items_daily;
 _col0
-------
   424
trino:acct10001> select count(*) from oci_usage_line_items;
 _col0
-------
  1768
 trino:acct10001> select count(*) from oci_usage_line_items_daily;
 _col0
-------
   166
```
OCI Tables:
```
postgres=# \dt reporting_oci*
                                        List of relations
  Schema   |                         Name                         |       Type        |  Owner
-----------+------------------------------------------------------+-------------------+----------
 acct10001 | reporting_oci_compute_summary_by_account_p           | partitioned table | postgres
 acct10001 | reporting_oci_compute_summary_by_account_p_2022_04   | table             | postgres
 acct10001 | reporting_oci_compute_summary_by_account_p_2022_05   | table             | postgres
 acct10001 | reporting_oci_compute_summary_by_account_p_default   | table             | postgres
 acct10001 | reporting_oci_compute_summary_p                      | partitioned table | postgres
 acct10001 | reporting_oci_compute_summary_p_2022_04              | table             | postgres
etc
 ```
 @lcouzens The only table that came up empty for me when I checked was the `reporting_ocicostentry` table. I wasn't quite sure what the purpose of that table was so I figured I would just point it out to you. 
 
 
*TLDR:*
This is awesome Luke, I think we are ready to move this into main after we finish investigating the smoke tests. 👍

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
86e86dc5-925f-4170-807a-dad5414592d9
eb3308ef-65cd-4fdf-b159-588091bb15b2

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4618cc43-0105-43a5-982e-86ee90ca79dd
5a20ad42-f410-4f10-a64e-5b22149394a2

**Pull request merged**
