### PR TITLE
COST-553 Add pvc to metrics

### PR DESCRIPTION
**Pull request by boaz0**
This adds "PVC" to metrics both in the API and in masu.

### CODE REVIEW

**Comment by boaz0** [comment]
The CI fails because of

```
Warning: Your Pipfile requires python_version 3.8, but you are using 3.6.9 (/usr/bin/python3).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
```

Now that's odd because I see it setups Python 3.8 so I am not sure why it fails.
In addition, running the tests on my machine it works fine (after upgrading to Python 3.8 of course).

**Review by cgoodfred — APPROVED** [review]
LGTM 👍

**Comment by boaz0** [comment]
I got regression in the unit tests after updating to master

**Comment by boaz0** [comment]
Never mind :grin:

**Review by dccurtis — APPROVED** [review]

**Comment by boaz0** [comment]
Thanks!

**Pull request merged**
