### PR TITLE
Sources: Use celery task to create Provider

### PR DESCRIPTION
**Pull request by maskarb**
#1890 This PR addresses the timing issue noted in #1890. All provider create/update events are handled in Celery.

- Use celery to create/update Provider. This has the added benefit of increasing our response time when PATCHing a source.
- Add `status` field to Sources table. Status is added to table during Provider creation or update. This status is sent to sources-api when a provider is created or updated.

I noticed that the status was not making its way to the sources-api when a Source was edited. This PR address that issue.

### CODE REVIEW

**Comment by adberglund** [comment]
If we're using celery to create the provider, we might consider looking at task priority https://docs.celeryproject.org/en/latest/userguide/routing.html#rabbitmq-message-priorities or setting up a celery worker to run priority tasks. Just in the event that our normal workers are backed up processing reports. Something to discuss before we do anything about it. @chambridge Thoughts?

**Comment by chambridge** [comment]
Is the focus of this to reduce latency? We could certainly investigate priority, but if this is mostly an impact from a PATCH, I'm kinda okay with seeing how we are overall. I'm not sure this API is going to be hit a ton by customers.

**Comment by chambridge** [comment]
I like the transition to a uniform code flow, but I'm still not clear on what happens if a source is created during an ingestion cycle ... is there the potential for this to take hours of waiting to create the provider? If not priority, should we spin up a `sources-worker` with our e2e templates to handle this queue of tasks (seems a bit resource heavy, but should work)?

**Comment by adberglund** [comment]
@chambridge @maskarb That's essentially what I was getting at with this potentially taking hours to process. Totally not unheard of to have a worker that handles specific queues for celery, and if we have one for this we can give it significantly fewer resources than the current workers.

**Comment by maskarb** [comment]
The celery tasks are added to a `sources` queue. I've created a `koku-sources-worker` pod which only handles the `sources` queue in this PR:
[https://github.com/RedHatInsights/e2e-deploy/pull/1223](https://github.com/RedHatInsights/e2e-deploy/pull/1223)

**Pull request merged**
