### PR TITLE
[COST-4670] Enable copy-on-write in Pandas

### PR DESCRIPTION
**Pull request by samdoran**
## Jira Ticket

[COST-4670](https://issues.redhat.com/browse/COST-4670)

## Description

Enable [copy-on-write in `pandas`](https://pandas.pydata.org/docs/dev/whatsnew/v2.2.0.html#copy-on-write). This should result in better memory usage and more predictable performance.

## Testing

1. Deploy koku
2. Run tests and monitor memory usage

## Notes

If this change has no negative impact, we should enable it now.

### CODE REVIEW

**Comment by lcouzens** [comment]
Right now this is likely a QE testing effort to evaluate the impact of any Memory improvements/degradations PRIOR to this being merged. Lets give QE time to test this and if they are satisfied they can be the ones to approve this PR for it to be merged.

**Comment by samdoran** [comment]
Tests are failing with `ChainedAssignmentError` when running `test_api_ocp_on_gcp_source_raw_calc` and `test_api_gcp_hcs_report_content`. This is [expected](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.errors.ChainedAssignmentError.html) when copy-on-write is enabled.

Need to identify where we are doing chained assignments and update the code.

**Pull request closed without merging**
