### PR TITLE
COST-2341 - move dev scripts to dev/scripts

### PR DESCRIPTION
**Pull request by djnakabaale**
Fixes [COST-2341](https://issues.redhat.com/browse/COST-2341)

Changes proposed in this PR:
* move dev scripts into dev/scripts
* separate deprecated scripts
* update paths to moved scripts in makefile

Testing Instructions:
- at the moment this is manual, just run any make commands in your terminal

---
Additional Context:

### CODE REVIEW

**Review by maskarb — COMMENTED** [review]
So far this looks great! I do have a couple comments:

**Review by djnakabaale — COMMENTED** [review]
@maskarb I've updated the readme in scripts dir with brief descriptions of the files and subfolder inside it. I think it can be helpful. What are your thoughts?

**Comment by djnakabaale** [comment]
> 

/reteset

**Review by maskarb — APPROVED** [review]
lgtm! Nicely done.

**Pull request merged**
