### PR TITLE
Add config info to status endpoint

### PR DESCRIPTION
**Pull request by Red-HAP**
## Jira Ticket

[COST-1718](https://issues.redhat.com/browse/COST-1718)

## Description

This will add a field for config on the response from the `status/` endpoint.

Review away!

image

## Testing

1. Checkout branch
2. Ensure koku is running
3. Hit `http://localhost:8000/api/cost-management/v1/status/`
4. Check result against example below. Except for field values, the structure should be the same (top-level keys, sub-keys)

### Example Response

```json
{
    "api_version": 1,
    "commit": "r.2020.01.23.0-1051-g09628e5c0",
    "modules": {
        "_cffi_backend": "1.14.5",
        "_csv": "1.0",
        "_ctypes": "1.1.0",
        "_decimal": "1.70",
        "adal": "1.2.7",
        "amqp": "2.6.1",
        "amqp.connection": "2.6.1",
        "argparse": "1.1",
        "asgiref": "3.4.0",
        "azure.common": "1.1.27",
        "azure.core": "1.15.0",
        "azure.core.pipeline.transport": "__version__",
        "azure.mgmt.core": "1.2.2",
        "azure.mgmt.costmanagement": "0.2.0",
        "azure.mgmt.resource.managedapplications": "18.0.0",
        "azure.mgmt.storage": "11.2.0",
        "azure.storage.blob": "12.8.1",
        "babel": "2.9.1",
        "billiard": "3.6.4.0",
        "boto3": "1.17.103",
        "botocore": "1.20.103",
        "botocore.docs.bcdoc": "0.16.0",
        "botocore.session": "1.20.103",
        "botocore.vendored.requests.packages.urllib3": "1.10.4",
        "botocore.vendored.six": "1.10.0",
        "cachetools": "4.2.2",
        "celery": "4.4.7",
        "certifi": "2021.05.30",
        "cffi": "1.14.5",
        "cgi": "2.6",
        "chardet": "4.0.0",
        "chardet.version": "4.0.0",
        "ciso8601": "2.1.3",
        "cryptography": "3.4.7",
        "cryptography.__about__": "3.4.7",
        "csv": "1.0",
        "ctypes": "1.1.0",
        "dateutil": "2.8.1",
        "decimal": "1.70",
        "distutils": "3.8.6",
        "django": "3.1.13",
        "django_extensions": "3.1.3",
        "django_filters": "2.4.0",
        "django_prometheus": "2.1.0",
        "django_redis": "5.0.0",
        "docutils": "0.16",
        "docutils.core": "0.16",
        "docutils.utils.roman": "1.4",
        "environ.environ": "('0', '4', '5')",
        "google.api_core": "1.30.0",
        "google.api_core.version": "1.30.0",
        "google.auth": "1.32.1",
        "google.auth.version": "1.32.1",
        "google.cloud.bigquery": "2.20.0",
        "google.cloud.bigquery._http": "2.20.0",
        "google.cloud.bigquery.version": "2.20.0",
        "google.cloud.version": "1.7.1",
        "google.protobuf": "3.17.3",
        "googleapiclient.mimeparse": "0.1.3",
        "grpc": "1.38.1",
        "grpc._grpcio_metadata": "1.38.1",
        "http.server": "0.6",
        "httplib2": "0.19.1",
        "httplib2.iri2uri": "1.0.0",
        "ibm_cloud_sdk_core.base_service": "3.10.0",
        "ibm_cloud_sdk_core.version": "3.10.0",
        "ibm_platform_services": "0.19.0",
        "ibm_platform_services.common": "0.19.0",
        "ibm_platform_services.version": "0.19.0",
        "idna": "2.10",
        "idna.idnadata": "13.0.0",
        "idna.package_data": "2.10",
        "ipaddress": "1.0",
        "jinja2": "2.11.3",
        "jinjasql": "0.1.8",
        "jmespath": "0.10.0",
        "json": "2.0.9",
        "jwt": "2.1.0",
        "kombu": "4.6.11",
        "logging": "0.5.1.2",
        "markupsafe": "2.0.1",
        "msrest": "0.6.21",
        "msrestazure": "0.6.4",
        "numpy": "1.21.0",
        "numpy.core": "1.21.0",
        "numpy.core._multiarray_umath": "3.1",
        "numpy.lib": "1.21.0",
        "numpy.linalg._umath_linalg": "0.1.5",
        "oauthlib": "3.1.1",
        "optparse": "1.5.3",
        "packaging": "20.9",
        "packaging.__about__": "20.9",
        "pandas": "1.2.5",
        "pandas.compat.numpy.function": "1.21.0",
        "patsy": "0.5.1",
        "patsy.version": "0.5.1",
        "pint": "0.17",
        "pkg_resources._vendor.packaging.__about__": "16.8",
        "pkg_resources._vendor.six": "1.10.0",
        "pkg_resources.extern.appdirs": "1.4.3",
        "pkg_resources.extern.packaging": "16.8",
        "pkg_resources.extern.pyparsing": "2.2.1",
        "pkg_resources.extern.six": "1.10.0",
        "platform": "1.0.8",
        "prestodb": "0.7.0",
        "prometheus_client.decorator": "4.0.10",
        "psutil": "5.8.0",
        "psycopg2": "2.9.1 (dt dec pq3 ext lo64)",
        "psycopg2._psycopg": "2.9.1 (dt dec pq3 ext lo64)",
        "pyarrow": "4.0.1",
        "pygments": "2.9.0",
        "pyparsing": "2.4.7",
        "pytz": "2021.1",
        "re": "2.2.1",
        "redis": "3.5.3",
        "requests": "2.25.1",
        "requests.__version__": "2.25.1",
        "requests.packages.chardet": "4.0.0",
        "requests.packages.chardet.version": "4.0.0",
        "requests.packages.idna": "2.10",
        "requests.packages.idna.idnadata": "13.0.0",
        "requests.packages.idna.package_data": "2.10",
        "requests.packages.urllib3": "1.26.6",
        "requests.packages.urllib3._version": "1.26.6",
        "requests.packages.urllib3.connection": "1.26.6",
        "requests.packages.urllib3.packages.six": "1.16.0",
        "requests.utils": "2.25.1",
        "requests_oauthlib": "1.3.0",
        "rest_framework": "3.12.4",
        "rest_framework_csv": "2.1.1",
        "scipy": "1.7.0",
        "scipy._lib._uarray": "0.5.1+49.g4c3f1d7.scipy",
        "scipy._lib.decorator": "4.0.5",
        "scipy.integrate._dop": "b'$Revision: $'",
        "scipy.integrate._ode": "$Id$",
        "scipy.integrate._odepack": " 1.9 ",
        "scipy.integrate._quadpack": " 1.13 ",
        "scipy.integrate.lsoda": "b'$Revision: $'",
        "scipy.integrate.vode": "b'$Revision: $'",
        "scipy.interpolate._fitpack": " 1.7 ",
        "scipy.interpolate.dfitpack": "b'$Revision: $'",
        "scipy.linalg._fblas": "b'$Revision: $'",
        "scipy.linalg._flapack": "b'$Revision: $'",
        "scipy.linalg._flinalg": "b'$Revision: $'",
        "scipy.linalg._interpolative": "b'$Revision: $'",
        "scipy.ndimage": "2.0",
        "scipy.optimize.__nnls": "b'$Revision: $'",
        "scipy.optimize._cobyla": "b'$Revision: $'",
        "scipy.optimize._lbfgsb": "b'$Revision: $'",
        "scipy.optimize._minpack": " 1.10 ",
        "scipy.optimize._slsqp": "b'$Revision: $'",
        "scipy.optimize.minpack2": "b'$Revision: $'",
        "scipy.signal.spline": "0.2",
        "scipy.sparse.linalg.eigen.arpack._arpack": "b'$Revision: $'",
        "scipy.sparse.linalg.isolve._iterative": "b'$Revision: $'",
        "scipy.special.specfun": "b'$Revision: $'",
        "scipy.stats.mvn": "b'$Revision: $'",
        "scipy.stats.statlib": "b'$Revision: $'",
        "six": "1.16.0",
        "socketserver": "0.4",
        "sqlparse": "0.4.1",
        "statsmodels": "0.12.2",
        "statsmodels.__init__": "0.12.2",
        "statsmodels.api": "0.12.2",
        "statsmodels.tools.web": "0.12.2",
        "tblib": "1.7.0",
        "ujson": "4.0.2",
        "unicodecsv": "0.14.1",
        "unicodecsv.py3": "1.0",
        "unittest.mock": "1.0",
        "uritemplate": "3.0.1",
        "urllib.request": "3.8",
        "urllib3": "1.26.6",
        "urllib3._version": "1.26.6",
        "urllib3.connection": "1.26.6",
        "urllib3.packages.six": "1.16.0",
        "vine": "1.3.0",
        "whitenoise": "5.2.0",
        "wsgiref.simple_server": "0.2",
        "yaml": "5.4.1",
        "zlib": "1.0"
    },
    "platform_info": {
        "system": "Linux",
        "node": "ddc6befdd97e",
        "release": "5.13.12-100.fc33.x86_64",
        "version": "#1 SMP Wed Aug 18 20:12:01 UTC 2021",
        "machine": "x86_64",
        "processor": "x86_64"
    },
    "python_version": "3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]",
    "rbac_cache_ttl": "30",
    "config": {
        "debug": true,
        "account_access_type": "db",
        "pvc_dir": "/var/tmp/masu",
        "volume_file_retention": 86400,
        "insights_local_report_dir": "/var/tmp/masu/insights_local",
        "tmp_dir": "/var/tmp/masu/processing",
        "warehouse_path": "data",
        "csv_data_type": "csv",
        "parquet_data_type": "parquet",
        "report_processing_batch_size": 100000,
        "aws_datetime_str_format": "%Y-%m-%dT%H:%M:%SZ",
        "ocp_datetime_str_format": "%Y-%m-%d %H:%M:%S +0000 UTC",
        "azure_datetime_str_format": "%Y-%m-%d",
        "masu_date_override": null,
        "masu_retain_num_months": 3,
        "masu_retain_num_months_line_item_only": 1,
        "reporting_decimal_precision": 9,
        "initial_ingest_num_months": 3,
        "ingest_override": false,
        "insights_kafka_host": "localhost",
        "insights_kafka_port": 29092,
        "insights_kafka_address": "localhost:29092",
        "hccm_topic": "platform.upload.hccm",
        "validation_topic": "platform.upload.validation",
        "kafka_connect": true,
        "retry_seconds": 10,
        "del_record_limit": 5000,
        "max_iterations": 3
    },
    "server_address": "localhost:8000"
}
```

### CODE REVIEW

**Review by myersCody — APPROVED** [review]
Sweet I can see the config in the status endpoint:
```
"config": {
        "debug": true,
        "account_access_type": "db",
        "pvc_dir": "/var/tmp/masu",
        "volume_file_retention": 86400,
        "insights_local_report_dir": "/var/tmp/masu/insights_local",
        "tmp_dir": "/var/tmp/masu/processing",
        "warehouse_path": "data",
        "csv_data_type": "csv",
        "parquet_data_type": "parquet",
        "report_processing_batch_size": 100000,
        "aws_datetime_str_format": "%Y-%m-%dT%H:%M:%SZ",
        "ocp_datetime_str_format": "%Y-%m-%d %H:%M:%S +0000 UTC",
        "azure_datetime_str_format": "%Y-%m-%d",
        "masu_date_override": null,
        "masu_retain_num_months": 3,
        "masu_retain_num_months_line_item_only": 1,
        "reporting_decimal_precision": 9,
        "initial_ingest_num_months": 2,
        "ingest_override": true,
        "insights_kafka_host": "localhost",
        "insights_kafka_port": 29092,
        "insights_kafka_address": "localhost:29092",
        "hccm_topic": "platform.upload.hccm",
        "validation_topic": "platform.upload.validation",
        "kafka_connect": true,
        "retry_seconds": 10,
        "del_record_limit": 5000,
        "max_iterations": 3
    },
```
Once we get the unit tests and smoke tests working we can move this one on into main.

**Review by maskarb — APPROVED** [review]
lgtm!

**Pull request merged**
