### PR TITLE
COST-2106: Remove unnecessary GCP partables from provider map.

### PR DESCRIPTION
**Pull request by myersCody**
In an effort to do only additive changes I am gonna do this issue in two prs. The first one (this pr) removed the unnecessary GCP partables from the provider map. Once no endpoint in production can attempt to pull data from these tables, we can merge in the 2nd pull request to delete the tables. 

--- 

Smoke Tests:
*01/17/2021*
- https://ci.ext.devshift.net/job/project-koku-koku-pr-check/3459/
- https://ci.ext.devshift.net/job/project-koku-koku-pr-check/3460/testReport/tests.rest_api.v1/test_source/test_api_gcp_source_raw_calc/

### CODE REVIEW

**Comment by myersCody** [comment]
Successful Smokes: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/3471/

**Review by maskarb — APPROVED** [review]
lgtm!

**Pull request merged**
