### PR TITLE
Enabling monthly resolution with start/end date params

### PR DESCRIPTION
**Pull request by lcouzens**

### CODE REVIEW

**Review by dlabrecq — APPROVED** [review]

**Comment by lcouzens** [comment]
smoke test failures are expected due to QE negative test cases. I will put up a MR for that shortly. Errors are related to AWS creds which is not a problem.

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Review by dlabrecq — COMMENTED** [review]
LGTM

**Pull request merged**
