### PR TITLE
add gunicorn logger to django config

### PR DESCRIPTION
**Pull request by maskarb**
Today, gunicorn logs are excluded from cloudwatch.

Changes proposed in this PR:
* add the gunicorn loggers to the django logging config so that cloudwatch becomes one of the handlers for gunicorn logs.
* these changes result in a slight format change:
current logs:
```
[2022-05-19 08:50:55,228] INFO None {'method': 'GET', 'path': '/api/cost-management/v1/status/', 'status': 200, 'request_id': None, 'account': None, 'username': None, 'is_admin': False, 'response_time': '45.89 ms'}
10.10.10.10 - - [18/May/2022:21:14:47 +0000] "GET /api/cost-management/v1/status/ HTTP/1.1" 200 7969 "-" "kube-probe/1.23"
```
this is how it will look after this PR merges:
```
[2022-05-18 21:14:47,865] INFO None {'method': 'GET', 'path': '/api/cost-management/v1/status/', 'status': 200, 'request_id': None, 'account': None, 'username': None, 'is_admin': False, 'response_time': '5037.82 ms'}
[2022-05-18 21:14:47,866] INFO None 10.10.10.10 - - "GET /api/cost-management/v1/status/ HTTP/1.1" 200 8008 "-" "kube-probe/1.22"
```

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
32706b2c-eef3-476e-8788-27eb52e9a6f5
8d015891-4ad9-4bc7-bec9-9b51d49cb9e3

**Review by abaiken — APPROVED** [review]

**Review by lcouzens — APPROVED** [review]

**Pull request merged**
