### PR TITLE
Cost 2216/2217/2218 - Adding affective cost metric to cost model calculations

### PR DESCRIPTION
**Pull request by lcouzens**
This PR add's the ability to store and calculate based from the new effective cost metric.

Testing:
- Check new metrics are visible at http://localhost:8000/api/cost-management/v1/metrics/
- Add ocp source/data
- Create a cost model using effective cost metrics
- Verify calculations are correctly applied to source data

### CODE REVIEW

**Review by adberglund — COMMENTED** [review]
I thought a little more about this, and at this point we're already at daily data, and we might want to catch the `greatest()` at the hourly level, so let's talk next week about getting it in the summary sql maybe.

**Comment by lcouzens** [comment]
Requires 3412

**Comment by lcouzens** [comment]
Smoke run failures which are fully expected until the QE MR's are merged.
test_api_ocp_metrics 
test_api_cost_model_ocp_crud

**Review by ddonahue007 — DISMISSED** [review]
lgtm

**Review by adberglund — APPROVED** [review]

**Pull request merged**
