### PR TITLE
Makefile (replace remove with delete)

### PR DESCRIPTION
**Pull request by myersCody**
## Jira Ticket

delete = remove & remove = delete

Example:
```(koku) cmyers@cmyers1-mac koku % make delete-test-db
Test DB (test_postgres) has been removed.
(koku) cmyers@cmyers1-mac koku % make remove-test-customer-data
/Users/cmyers/.local/share/virtualenvs/koku-WwpPTI0J/bin/python /Users/cmyers/Projects/cost_mgmt/koku/dev/scripts/delete_test_sources.py
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/e331d32a-b047-4d46-9c60-28b599767932/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/66572ed3-7a96-4c1a-a970-26c6d82b2e77/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/184262c7-d358-47c8-ab53-91453a491477/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/35187fa9-d41f-4343-b46e-3dd4dee25e05/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/1d3a362b-2a0d-4988-a44e-63225ac030fa/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/c3544f41-5210-4513-be2d-9333aac84dfb/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/445548b9-4d04-468c-b60b-27f76d4f4eff/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/1d719ffd-c7c9-472f-969d-faadb31dec93/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/a300869e-1e30-4196-8280-954f54c794f5/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/48f98afc-a9d8-4a90-9018-a2321b66872e/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/7452beba-7503-4d06-8fb2-77a4833a87fa/
<Response [204]>
Calling DELETE http://127.0.0.1:8000/api/cost-management/v1/sources/77a8bdf0-3d6b-4963-95f9-fce2d32e753e/
<Response [204]>
/Users/cmyers/.local/share/virtualenvs/koku-WwpPTI0J/bin/python /Users/cmyers/Projects/cost_mgmt/koku/dev/scripts/delete_cost_models.py
Calling http://127.0.0.1:8000/api/cost-management/v1/cost-models/8bd01c64-6016-4003-adb4-9cf6208aeb4a/
<Response [204]>
Calling http://127.0.0.1:8000/api/cost-management/v1/cost-models/8f82a87e-b924-41db-a06a-3d4475542c97/
<Response [204]>
Calling http://127.0.0.1:8000/api/cost-management/v1/cost-models/3afe7d44-388b-45f3-b84e-433eab2c9a21/
<Response [204]>
Calling http://127.0.0.1:8000/api/cost-management/v1/cost-models/bc36447c-e335-4088-aedd-0e5101919084/
<Response [204]>
Calling http://127.0.0.1:8000/api/cost-management/v1/cost-models/b5c72e09-7c92-4ad0-92d4-8380f39b7dc8/
<Response [204]>
Calling http://127.0.0.1:8000/api/cost-management/v1/cost-models/3986e328-7e0e-4ec2-83a7-b3a91f2517e0/
<Response [204]>```

### CODE REVIEW

**Review by djnakabaale — COMMENTED** [review]
Would it be more helpful to pick `remove` or `delete` and stick with it?

**Comment by myersCody** [comment]
> Would it be more helpful to pick `remove` or `delete` and stick with it?

Yeah, I thought about that, but didn't want to mess up anybody's current workflow. I figured this would be a kind way of giving everybody the option to decide if they are `delete` people or `remove` people.

**Review by lcouzens — CHANGES_REQUESTED** [review]
Pick one and force everyone to change to it! :grin: In all seriousness its not _that_ big of a deal BUT lets not maintain two things if we dont need to.

**Comment by myersCody** [comment]
> Pick one and force everyone to change to it! 😁 In all seriousness its not _that_ big of a deal BUT lets not maintain two things if we dont need to.

sure

**Comment by maskarb** [comment]
I'm just gonna leave this link here for inspiration:
https://dribbble.com/shots/14989130-Remove-vs-delete

(I do not feel strongly one way or another, just tell me which you prefer)

**Review by djnakabaale — APPROVED** [review]
Thanks for doing this cleanup, lgtm 👍🏾

**Review by maskarb — APPROVED** [review]

**Review by lcouzens — APPROVED** [review]

**Review by samdoran — APPROVED** [review]

**Comment by myersCody** [comment]
😃 so many approvals 🥇 (wipes tear)

**Pull request merged**
