### PR TITLE
GCP customer filtered data flow

### PR DESCRIPTION
**Pull request by lcouzens**
## Jira Ticket

[COST-3509](https://issues.redhat.com/browse/COST-3509)

## Description

This change will enable GCP storage only sources with post report ingestion

## Testing

1. Checkout Branch
2. Restart Koku
3. Create a storage-only GCP source - data-source includes
    {
    "bucket":"my-bucket",
    "storage-only": "True"
    },
4.Post to the new endpoint a marketplace report stored in S3
    a. Endpoint: /api/cost-management/v1/ingress/reports/
    b. Example: {"source": "9e7159f1-c5fe-4455-9881-ee730654cf84", "reports_list": ["MY_container/2023/01/18/34472771-acab-4ca4-8c6a-8721d9b91188/cc3ecf82-9960-4f02-9a31-b9163f75e6b7.csv"]}
5. See that the data is ingested correctly

## Notes

...

### CODE REVIEW

**Review by myersCody — DISMISSED** [review]
Awesome work Luke!

```
 {'message': 'mark_manifest_complete called with args: schema_name: org1234567, provider_type: GCP, provider_uuid: e74c2cf0-074f-4948-aa1c-35aa1c25a611, ingress_report_uuid: 6c99dd77-e277-435a-8d4d-ad3237c07bce, synchronous: False, queue_name: None, tracing_id: 2023-02-23|a84f27f7-99f2-4a4d-88d0-0ce1b95989b2, manifest_list: [1]', 'tracing_id': '2023-02-23|a84f27f7-99f2-4a4d-88d0-0ce1b95989b2'}
 ```

**Comment by lcouzens** [comment]
OCI raw calc smoke test failure.

**Review by myersCody — APPROVED** [review]
LGTM! Glad I was able to help with that filename part causing duplicate data! Awesome work Luke!

**Pull request merged**
