### PR TITLE
Bumping masu liveness probe

### PR DESCRIPTION
**Pull request by lcouzens**
Fixes [COST-####](https://issues.redhat.com/browse/COST-####)

Changes proposed in this PR:
*
*

Testing Instructions:
1. Run `this command` ...
2. Ingest this data `with this other command` ...
3. Expect to see this result:
   ```
   GET http://localhost:8000/api/endpoint

   {json: response}
   ```
4.
5.

---
Additional Context:

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3db8ebe4-ff04-4ac5-b481-5919435356c8
6cab56b1-f01c-450a-b2e3-123f756ac2e5

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
c19b9fa7-0ac7-4389-a55c-e846e235355f
d02a7b82-7487-409b-b64b-ee6fee4d1623

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
73700d6c-ae43-492f-a8e8-b65bb3932f15
7adfd337-a1f9-490b-9fce-dfea6110d988

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
94d793bf-9ee0-485b-b039-cef0afff1753
a0715c4b-28ef-4182-9845-9bc17e45dd95

**Review by maskarb — APPROVED** [review]

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
bedc9bb5-35fb-4dbc-992f-43a4dcedfece
d43a92b6-d85d-49f2-bf38-49cd4ac83148

**Pull request merged**
