### PR TITLE
Revert "Using strpos seems to speed up query"

### PR DESCRIPTION
**Pull request by maskarb**
Reverts project-koku/koku#3363

### CODE REVIEW

**Comment by adberglund** [comment]
Did you see https://github.com/project-koku/koku/pull/3371 ?

**Comment by cgoodfred** [comment]
> Did you see #3371 ?

The test run from that PR wasn't great: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/3247/testReport/

So that change may not have been a smooth one, hopefully the test run on this branch will tell us more.

**Pull request closed without merging**
