### PR TITLE
Changes and deploy yaml to support migration running via CJI

### PR DESCRIPTION
**Pull request by Red-HAP**
## Jira Ticket

[COST-2076](https://issues.redhat.com/browse/COST-2076)

## Description

Support running migrations as part of the init container as well as via a CJI job deploy

### Base Setup

* `export NAMESPACE=$(bonfire namespace reserve --duration 12)`
* Login to https://console-openshift-console.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/k8s/cluster/projects and copy login command
* Paste login command to local CLI
* `oc project $NAMESPACE`
* `bonfire process hccm --source=appsre --local-config-path dev/config.yaml --no-remove-resources koku --no-remove-resources presto --no-remove-resources hive-metastore --set-parameter rbac/MIN_REPLICAS=1 --namespace $NAMESPACE | oc apply -f - -n $NAMESPACE`
* On the OCP project web terminal, find the koku-db pod and get to the terminal

Also, the stanza added to my private config yaml for these tests was:

```yaml
    - name: db-migrations
      host: github
      repo: project-koku/koku
      path: deploy/koku-migrations-cji.yaml
      ref: 072b2a1ec5c9f6e034172cd456c9a106720b4f64
      parameters:
        IMAGE: quay.io/48_41_50/local_koku
        IMAGE_TAG: 072b2a1
        S3_BUCKET_NAME: koku-eph-s3
        # Migration directive is optional and should be in the form of:
        # <app>[:<migration>][,<app>[:<migration>]...]
        # Ex: "reporting:0200,api:0050"
        # Ex: "reporting:0200"
        # Ex: "reporting"
        # Ex: ""
        _MIGRATION_DIRECTIVE: ""
```

### Test Setup

* `for res in $(oc get pods -n $NAMESPACE | grep db-migrations-koku-db | cut -d ' ' -f 1); do     oc delete -n $NAMESPACE pod/$res; done`
* `for res in $(oc get clowdjobinvocation -n $NAMESPACE | grep koku-db | cut -d ' ' -f 1); do     oc delete -n $NAMESPACE clowdjobinvocation/$res; done`
* `for res in $(oc get pods -n $NAMESPACE | grep db-migrations-koku-db | cut -d ' ' -f 1); do     oc delete -n $NAMESPACE pod/$res; done`
* `bonfire process hccm --local-config-path ./dev/config.yaml --source=appsre --namespace $NAMESPACE --no-get-dependencies --component db-migrations --no-remove-resources db-migrations | oc apply -f - -n $NAMESPACE`

### Test 1

Normal deploy of current branch. 

#### Expected Result

This change should have zero effects on a normal deploy and startup.

#### Observed Result

From a scratch deploy, migrations ran successfully. This was before a source was created so only the `public` schema tables were created.

### Test 2

Deploy CJI with a migration revert

This will be done by submitting a reset of api.0050 migration. The `_MIGRATION_DIRECTIVE` variable was set to `"api:0049"`.

#### Expected Result

Specified app should revert migrations up to (but not including) the target migration. Any dependencies should also be reverted. (This is handled by Django)

##### Log

Note that this also unapplied all migrations related to `api.0050`

```
🤔 : Migrations should be run
⌚ : Running Migrations api 0049
celery broker using redis url: redis://db-migrations-redis.ephemeral-31.svc:6379/1
Source status schedule: <crontab: */30 * * * * (m/h/d/dM/MY)>
=== Running migrate for schema public
Operations to perform:
  Target specific migration: 0049_auto_20210818_2208, from api
Running migrations:
  Rendering model states...
 DONE
  Unapplying reporting.0209_gcp_partables...
 OK
  Unapplying reporting.0208_savingsplan_markup_fields...
 OK
  Unapplying reporting.0207_auto_20211115_2234...
 OK
  Unapplying reporting.0206_auto_20211115_1322...
 OK
  Unapplying reporting.0205_ocpall_perspective_db_defaults...
 OK
  Unapplying reporting.0204_auto_20211110_2118...
 OK
  Unapplying reporting.0203_auto_20211108_1626...
 OK
  Unapplying reporting.0202_azure_partables...
 OK
  Unapplying reporting.0201_ocp_partables...
 OK
  Unapplying reporting.0200_ocpgcp_partables...
 OK
  Unapplying reporting.0199_aws_perspective_colname_idx...
 OK
  Unapplying reporting.0198_aws_matviews_to_partables...
 OK
  Unapplying api.0050_exchangerates...
 OK
✅ : Migrations complete!
```

##### Database

Note that the `0050` migration is missing.

```
koku=# select app, name from django_migrations where app = 'api' order by name ;
 app |                  name                  
-----+----------------------------------------
 api | 0001_initial
 api | 0030_auto_20201007_1403
 api | 0031_clone_schema
 api | 0032_presto_delete_log_trigger_func
 api | 0033_sources_name_text
 api | 0034_remove_sources_endpoint_id
 api | 0035_reapply_partition_and_clone_func
 api | 0036_reapply_check_migrations_func
 api | 0037_auto_20210223_2136
 api | 0038_drop_app_needs_migrations_func
 api | 0039_create_hive_db
 api | 0040_auto_20210318_1514
 api | 0041_array_subtract_dbfunc
 api | 0042_reapply_clone_func
 api | 0043_apply_turbo_schema_clone_func
 api | 0044_auto_20210505_1747
 api | 0045_update_django_migration_sequences
 api | 0046_jsonb_sha256_text
 api | 0047_update_django_migration_sequences
 api | 0048_new_partition_manager_func
 api | 0049_auto_20210818_2208
(21 rows)
```

### Test 3

Deploy CJI with a migration

This will reapply specifically the `api.0050` migration. The `_MIGRATION_DIRECTIVE` variable was set to `"api:0050"`.

#### Expected Result

Only migration `api.0050` will be applied

##### Log

Note that only `api.0050` was applied

```
🤔 : Migrations should be run
⌚ : Running Migrations api 0050
celery broker using redis url: redis://db-migrations-redis.ephemeral-31.svc:6379/1
Source status schedule: <crontab: */30 * * * * (m/h/d/dM/MY)>
=== Running migrate for schema public
Operations to perform:
  Target specific migration: 0050_exchangerates, from api
Running migrations:
  Applying api.0050_exchangerates...
 OK
✅ : Migrations complete!
```

##### Database

Note that `api.0050` is present now.

```
koku=# select app, name from django_migrations where app = 'api' order by name;     
 app |                  name                  
-----+----------------------------------------
 api | 0001_initial
 api | 0030_auto_20201007_1403
 api | 0031_clone_schema
 api | 0032_presto_delete_log_trigger_func
 api | 0033_sources_name_text
 api | 0034_remove_sources_endpoint_id
 api | 0035_reapply_partition_and_clone_func
 api | 0036_reapply_check_migrations_func
 api | 0037_auto_20210223_2136
 api | 0038_drop_app_needs_migrations_func
 api | 0039_create_hive_db
 api | 0040_auto_20210318_1514
 api | 0041_array_subtract_dbfunc
 api | 0042_reapply_clone_func
 api | 0043_apply_turbo_schema_clone_func
 api | 0044_auto_20210505_1747
 api | 0045_update_django_migration_sequences
 api | 0046_jsonb_sha256_text
 api | 0047_update_django_migration_sequences
 api | 0048_new_partition_manager_func
 api | 0049_auto_20210818_2208
 api | 0050_exchangerates
(22 rows)
```

Also note that `reporting` migrations > `0197` are not present.

```
koku=# select app, name from django_migrations where app = 'reporting' and name >= '0198';
 app | name 
-----+------
(0 rows)
```

### Test 4

Deploy CJI with no migrations.

#### Expected result

Any remaining migrations should be applied. This should be the reporting migrations that were dependent on `api.0050`

The `_MIGRATION_DIRECTIVE` variable was set to `""`.

#### Observed Result

Only the reporting migrations were applied that had been unapplied when removing `api.0050`

##### Log

```
🔎 : Checking to see if migrations should be run...
[2021-11-30 18:06:21,895] INFO None Checking app migrations via database function
[2021-11-30 18:06:21,899] INFO None Migrations should be run.
🤔 : Migrations should be run
⌚ : Running Migrations
celery broker using redis url: redis://db-migrations-redis.ephemeral-31.svc:6379/1
Source status schedule: <crontab: */30 * * * * (m/h/d/dM/MY)>
=== Running migrate for schema public
Operations to perform:
  Apply all migrations: api, auth, contenttypes, cost_models, reporting, reporting_common, sessions
Running migrations:
  Applying reporting.0198_aws_matviews_to_partables...
 OK
  Applying reporting.0199_aws_perspective_colname_idx...
 OK
  Applying reporting.0200_ocpgcp_partables...
 OK
  Applying reporting.0201_ocp_partables...
 OK
  Applying reporting.0202_azure_partables...
 OK
  Applying reporting.0203_auto_20211108_1626...
 OK
  Applying reporting.0204_auto_20211110_2118...
 OK
  Applying reporting.0205_ocpall_perspective_db_defaults...
 OK
  Applying reporting.0206_auto_20211115_1322...
 OK
  Applying reporting.0207_auto_20211115_2234...
 OK
  Applying reporting.0208_savingsplan_markup_fields...
 OK
  Applying reporting.0209_gcp_partables...
 OK
✅ : Migrations complete!
```

##### Database

No other `api` migrations applied:

```
koku=# select app, name from django_migrations where app = 'api' order by name desc limit 1;
 app |        name        
-----+--------------------
 api | 0050_exchangerates
(1 row)
```

The `reporting` migrations >= '0180` were applied

```
koku=# select app, name from django_migrations where app = 'reporting' and name >= '0198';
    app    |                name                 
-----------+-------------------------------------
 reporting | 0198_aws_matviews_to_partables
 reporting | 0199_aws_perspective_colname_idx
 reporting | 0200_ocpgcp_partables
 reporting | 0201_ocp_partables
 reporting | 0202_azure_partables
 reporting | 0203_auto_20211108_1626
 reporting | 0204_auto_20211110_2118
 reporting | 0205_ocpall_perspective_db_defaults
 reporting | 0206_auto_20211115_1322
 reporting | 0207_auto_20211115_2234
 reporting | 0208_savingsplan_markup_fields
 reporting | 0209_gcp_partables
(12 rows)
```

### CODE REVIEW

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Comment by lcouzens** [comment]
Smoke tests actually all passed :suspect: Ignore the failures they are all related to the fact the tests started before midnight but completed afterwards Nov 18-19 really breaks some tests :smile:

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Review by maskarb — APPROVED** [review]
Looks good to me!

**Pull request merged**
